(() => {
  'use strict';
  const MODULES = [
    { id: 1, title: 'AI Foundations', subtitle: 'Core AI concepts, prompting, verification and responsible use.', count: 6 },
    { id: 2, title: 'Microsoft 365 Copilot at Work', subtitle: 'Use Copilot where work already lives across Microsoft 365.', count: 6 },
    { id: 3, title: 'Analysis & Decision Support', subtitle: 'Turn verified evidence into comparisons, recommendations and decision briefs.', count: 6 },
    { id: 4, title: 'Safe & Responsible AI', subtitle: 'Privacy, policy, verification, governance and human accountability.', count: 5 },
    { id: 5, title: 'Automation & AI Systems', subtitle: 'Build controlled, repeatable workflows and useful AI-assisted systems.', count: 5 },
    { id: 6, title: 'Implementation & Capstone', subtitle: 'Apply the Academy method to a practical workplace implementation.', count: 4 }
  ];

  const LESSONS = [
    L(1,1,'Prompting for lending work','A useful prompt tells Copilot what to create, which work information to use and what must be checked before the result is used. You remain responsible for the final result.','An approved monthly quality report shows that some lending staff are not fully identifying customer needs and are relying on coaches to find the correct guidance. Regional leaders need a short coaching note explaining the two issues and the improvement expected.','Write the instruction you would give Copilot. Ask for a short coaching note for regional leaders, use only the approved quality report and say what you will check before sharing it.','Which instruction gives Copilot a clear job and keeps you responsible for the result?',['Write a convincing coaching message and make it sound confident.','Create the coaching note from the approved report, then let me check the important details before sharing it.','Use every document available and decide what the lending staff should do.'],1,'Lending coaching prompt','Correct. Copilot has a clear task and source, and a person checks the result before it is shared.','Not quite. Choose the instruction that names the task, uses the approved report and includes a final check.'),
    L(1,2,'What AI can do — and where judgement stays human','AI can help organise evidence and draft an explanation. It cannot decide which unsupported explanation is true or take responsibility for the final coaching decision.','An approved report confirms that application processing slowed last month. Copilot suggests three possible causes, but the report supports only one of them. You need a summary that does not present guesses as facts.','Tell Copilot to list what the report confirms, separate any possible explanations and clearly mark what a person still needs to investigate.','What is the safest role for Copilot in this task?',['Choose the most likely cause and make the final coaching decision.','Organise the evidence and draft the summary while a person checks the facts and makes the decision.','Remove every possible explanation, even when it is clearly labelled.'],1,'Fact and possibility prompt','Correct. Copilot can organise and draft, while a person checks the evidence and owns the decision.','Not quite. Copilot can support the work, but a person must confirm the facts and make the final decision.'),
    L(1,3,'Choosing the right AI task','A broad job becomes easier to control when it is split into clear steps. Each step should produce something you can check before using it in the next step.','You have approved notes from a lending capability meeting. Your manager needs the main themes, a list of agreed actions and a short follow-up email to regional leaders.','Write three Copilot tasks in order: first identify the themes, then list the agreed actions, then draft the email. Show where you would check the notes before moving to the next task.','Why split this work into three tasks?',['Each result can be checked before it is used in the next step.','It guarantees every Copilot answer will be correct.','It allows Copilot to make the final decisions by itself.'],0,'Three-step AI task plan','Correct. Smaller tasks make the work easier to understand and check as it moves forward.','Not quite. The purpose is to make each result clear and checkable before it is reused.'),
    L(1,4,'Verify before you use','Checking an AI answer means comparing important statements with the approved source. If the source does not support a statement, it must be corrected, removed or clearly flagged.','Copilot drafts a coaching note saying a particular lending policy caused a recurring quality issue. The approved coaching notes describe the issue, but they do not contain that policy or prove the cause.','Tell Copilot to show the source behind each important statement and flag anything the coaching notes do not support. Explain what you would check before using the draft.','Which Copilot output needs the strongest check?',['A suggested heading for the coaching note.','A statement claiming that a lending policy caused the quality issue.','Three possible email subject lines.'],1,'Verification prompt','Correct. A policy claim could affect coaching or decisions, so it must be checked against an approved source.','Not quite. Choose the output that presents an important policy claim as fact.'),
    L(1,5,'Safe AI from the first prompt','Before using AI, keep the work in an approved workplace system and remove personal information that is not needed. Share only the minimum information required for the task.','You have three coaching examples containing customer names, account numbers, contact details and descriptions of staff coaching issues. You need help identifying common coaching themes, but the customers do not need to be identified.','Rewrite the task for an approved workplace AI system. State which customer details must be removed and ask it to use only the coaching information needed to identify the themes.','What is the safest way to prepare this task?',['Use the approved system, remove identifying details and include only the coaching information needed.','Upload everything first and ask Copilot to remove the customer details later.','Use any AI tool as long as you call the information confidential.'],0,'Safe AI task checklist','Correct. The task stays in an approved system and unnecessary customer information is removed before use.','Not quite. Customer details should be removed before the task enters an approved workplace AI system.'),
    L(1,6,'Foundation workflow challenge','Safe workplace AI use follows a clear path: choose approved information, give AI one clear task, check its draft and let a person make the final decision.','You must prepare a one-page coaching brief for national lending leaders. You have approved meeting notes, a quality report, coaching notes and the current policy document. The brief must describe confirmed issues, agreed actions and anything still requiring investigation.','Describe the steps you would follow from selecting the approved information to checking the final brief. Include what Copilot would do and what decisions must remain with you.','Which sequence keeps the work controlled from start to finish?',['Ask Copilot for the final brief, share it and check it only if someone questions it.','Choose approved sources, give Copilot a clear task, check the draft against those sources and make the final decision yourself.','Upload everything available and let Copilot decide which information and actions matter.'],1,'Controlled AI workflow','Correct. The information, AI task, checks and final human decision are clear at every stage.','Not quite. Choose the sequence that starts with approved information and keeps checking and final responsibility with a person.'),

    L(2,1,'Copilot in Teams','Use Copilot in Teams when the evidence lives in a meeting or chat. Ask for themes, decisions, unresolved questions and actions, then check the summary against the meeting context before reuse.','A national lending capability call contains updates from several regions and agreed next actions.','Write a Teams Copilot prompt that extracts verified themes, decisions and actions without inventing missing context.','What should happen before a Teams summary is reused?',['Check important points against the meeting context and available transcript or notes.','Forward it immediately because Copilot had access to the meeting.','Ask Copilot to make the summary more confident.'],0,'Teams meeting summary prompt'),
    L(2,2,'Copilot in Outlook','In Outlook, AI is useful for summarising long threads, drafting replies and adapting tone. Verify names, dates, commitments and policy-sensitive claims before sending.','A long email thread between lending leaders needs a concise follow-up confirming what was agreed and what remains open.','Write an Outlook prompt for a concise follow-up that separates confirmed commitments from unresolved points.','Which detail deserves explicit checking before send?',['Font choice.','Names, dates, commitments and policy-sensitive statements.','Whether the draft sounds formal enough.'],1,'Outlook follow-up prompt'),
    L(2,3,'Copilot in Word','Word is the right context when the job is drafting or improving a document around known source material. Keep evidence visible and flag claims that require confirmation.','You have approved notes and need a one-page coaching brief for regional lending leaders.','Write a Word Copilot prompt that turns approved notes into a structured brief while flagging unsupported claims.','Why keep drafting close to the source document?',['It reduces copying, keeps context visible and makes review easier.','It guarantees Copilot will never add new facts.','It lets you skip human review.'],0,'Word briefing prompt'),
    L(2,4,'Copilot in Excel','Use Copilot in Excel to explore patterns, summarise structured data and explain calculations, but confirm the columns, filters, period and calculation logic behind each insight.','A quality workbook contains monthly return rates by region and issue type.','Write an Excel Copilot request that identifies the largest recurring patterns and states the exact data range and filters used.','What must be checked before acting on an Excel insight?',['The data range, filters, period and calculation logic.','Only the wording of the summary.','Whether the chart looks professional.'],0,'Excel analysis prompt'),
    L(2,5,'Move verified work across Microsoft 365','The safest cross-app workflow moves only checked information forward. Summarise where the evidence lives, verify it there, then use the trusted output in the next app.','A Teams meeting must become a Word coaching brief and then an Outlook follow-up.','Design the three-step Copilot workflow and show what gets checked before moving from one app to the next.','What should move between apps?',['Every AI-generated detail so context is never lost.','Only the information needed for the next task, after important points are verified.','A final decision made by Copilot.'],1,'M365 carry-forward workflow'),
    L(2,6,'Microsoft 365 workflow challenge','Microsoft 365 Copilot is most useful when each app does the job closest to its source and the human keeps control of verification and final use.','You need to turn a national Teams discussion, Excel results and approved Word guidance into a regional coaching update.','Build the complete M365 workflow, naming the app, AI task, verification step and handoff at each stage.','Which design is strongest?',['One giant prompt containing everything.','A sequence of app-specific tasks with verification between handoffs.','Use whichever app opens first and copy the result everywhere.'],1,'M365 workflow map'),

    L(3,1,'Ask better analysis questions','Good AI analysis begins with a question that names the decision, evidence, period, comparison and limits. The goal is not more analysis; it is useful evidence for a defined workplace decision.','Regional application-quality results vary across the last three months.','Write an analysis question that specifies the period, comparison, evidence and what must not be inferred.','What makes an analysis question useful?',['It defines the decision, evidence, comparison and limits.','It asks AI to find anything interesting.','It requests as many charts as possible.'],0,'Analysis question template'),
    L(3,2,'Compare regions without losing context','Comparisons need consistent definitions, time periods and denominators. AI can surface differences, but the human must check that like is being compared with like.','Two regions show different return rates, but one handled a very different application mix.','Write a prompt that compares the regions while requiring Copilot to state the denominator, period and known context differences.','What is the main comparison risk?',['Using different definitions or denominators and treating the results as equivalent.','The regions having different names.','The summary being too short.'],0,'Regional comparison prompt'),
    L(3,3,'Use Power BI as evidence, not decoration','Power BI can surface patterns quickly, but a dashboard view is only a representation of underlying data. Confirm filters, time range, metric definitions and drill-through evidence before carrying a finding forward.','A Power BI dashboard appears to show a sudden rise in one quality issue.','Write the checks you would perform before describing the rise as a confirmed trend.','What should be verified first?',['Filters, period, metric definition and underlying evidence.','The dashboard theme colour.','Whether the visual is large enough for a presentation.'],0,'Power BI verification checklist'),
    L(3,4,'Separate pattern from cause','AI is good at spotting associations, but association is not proof of cause. Use language that separates what the data shows from possible explanations that need more evidence.','Returns increased after a process change, and Copilot says the change caused the increase.','Rewrite the analysis instruction so confirmed patterns and possible causes are reported separately.','Which statement is safest?',['The process change caused the increase.','Returns increased after the change; the available evidence does not yet establish cause.','AI identified the cause, so further evidence is optional.'],1,'Pattern vs cause prompt'),
    L(3,5,'Turn analysis into a decision brief','A useful decision brief links evidence to options without hiding uncertainty. It should state the question, confirmed findings, limits, options, risks and the decision required.','You need to brief lending leaders on three recurring quality issues and possible coaching responses.','Write a prompt for a one-page decision brief using only verified findings and clearly labelling uncertainty.','What belongs in a strong decision brief?',['Confirmed findings, limits, options, risks and the decision required.','Only the recommended option.','Every detail from the source data.'],0,'Decision brief prompt'),
    L(3,6,'Analysis challenge','Strong AI-assisted analysis keeps definitions, evidence, uncertainty and human decision-making visible from question through recommendation.','You have Excel data, a Power BI dashboard and regional notes that tell slightly different stories.','Design the analysis workflow that reconciles the sources and produces a verified recommendation.','What should happen when sources disagree?',['Choose the source with the clearest chart.','Investigate the difference, document the limitation and avoid claiming certainty until resolved.','Average the results and continue.'],1,'Verified analysis workflow'),

    L(4,1,'Minimise sensitive information','Use the minimum data necessary for the task. Removing unnecessary identifiers reduces risk without preventing AI from helping with structure, summarisation or analysis.','A set of coaching examples contains customer names, account references and detailed notes.','Rewrite the AI task to use only the information necessary for the coaching purpose.','What is the safest data principle?',['Minimum necessary information for the approved task.','Maximum context produces maximum safety.','Sensitive information is safe whenever it is useful.'],0,'Data minimisation checklist'),
    L(4,2,'Policy and approved-tool boundaries','Workplace AI operates inside organisational policy, approved-tool rules and access controls. When a boundary is unclear, stop and confirm rather than inventing a permission.','A lending coach asks you to upload a customer case file containing names, account numbers and income details to a public AI website that is not listed as an approved workplace tool. They want a quick summary before a regional meeting.','Write what you would say to the coach. State that you will not upload the file, then name the approval and information-handling checks you would complete before using any AI system.','What should happen when approval is unclear?',['Confirm the approved-tool and information-handling rules first.','Use the tool for a small test because the risk is limited.','Remove the file name and proceed.'],0,'AI policy boundary check'),
    L(4,3,'Bias and uneven evidence','AI can reproduce bias in its sources or amplify uneven evidence. Check whether groups, regions or cases are represented consistently before using output to shape coaching or decisions.','A summary suggests one region has weaker capability, but the underlying sample sizes differ sharply.','Write a review step that checks representation, sample size and alternative explanations before the conclusion is used.','What is the main safeguard?',['Check the evidence coverage and whether the comparison is fair before interpreting the result.','Ask AI to remove any negative wording.','Use the largest region as the benchmark automatically.'],0,'Fairness review prompt'),
    L(4,4,'Traceability and human accountability','Important AI-supported work should make it possible to trace where key claims came from, what was verified, what changed and who made the final decision.','A coaching brief is updated several times with AI assistance before it is shared nationally.','Design a simple traceability note recording sources, verification and final human approval.','Why keep traceability?',['So important claims and decisions can be reviewed and explained later.','So AI can approve future versions automatically.','To make the document longer.'],0,'AI traceability note'),
    L(4,5,'Responsible AI challenge','Responsible AI is not a separate final check. It is built into source choice, data minimisation, policy boundaries, verification, fairness, traceability and human accountability.','You must review an AI-assisted national coaching brief before release.','Create the final responsible-use checklist you would apply before approval.','Which approach is strongest?',['Run one final spelling check.','Check source, privacy, policy, evidence, fairness, traceability and human approval.','Ask AI whether its own answer is safe.'],1,'Responsible AI release checklist'),

    L(5,1,'Find repeatable work worth improving','Automation starts with a stable, repeated process. Choose work with clear inputs, outputs and review points rather than automating a vague or high-risk decision.','Regional coaching teams repeatedly turn approved quality results into a standard weekly summary.','Map the current process and identify the repeatable steps AI could assist without taking the final decision.','What is the best automation candidate?',['A repeatable task with clear inputs, outputs and review points.','Any task that consumes time.','A judgement-heavy decision with no standard process.'],0,'Automation candidate map'),
    L(5,2,'Design reusable prompt templates','A prompt template captures the stable parts of a task while leaving controlled fields for the source, audience, period and output. Reuse should improve consistency without hiding the need to verify each run.','Lending coaches create the same weekly quality summary for different regions.','Create a reusable prompt template with clearly marked fields and a required verification step.','What makes a prompt template safe to reuse?',['Stable structure plus variable fields and a verification requirement.','Removing all boundaries so it works for more tasks.','Using the previous output as the source every week.'],0,'Reusable prompt template'),
    L(5,3,'Put human checkpoints in the workflow','Human checkpoints belong where the risk or consequence increases: before sensitive data enters, before unsupported claims carry forward, and before an external or consequential action occurs.','An AI-assisted workflow drafts a weekly coaching brief and prepares an Outlook message.','Mark the human checkpoints and what must be reviewed at each one.','Where is a human checkpoint most important?',['Before consequential information is shared or acted on.','Only after the entire workflow is complete.','Human checkpoints are unnecessary if the template is approved.'],0,'Human checkpoint map'),
    L(5,4,'Pilot before you scale','A controlled pilot tests value, quality, exceptions and risk on a small scope before expansion. Define success and stop conditions before the pilot begins.','A proposed AI-assisted coaching workflow could be used across all regions.','Design a four-week pilot with scope, measures, failure criteria and a review point before expansion.','Why pilot first?',['To gather evidence on value, risk and failure modes before scaling.','To make the workflow look more innovative.','To avoid defining success measures until after launch.'],0,'AI pilot plan'),
    L(5,5,'Automation challenge','A strong AI system combines repeatable work, approved inputs, explicit verification, human ownership, traceability and measured pilots. Scale only when evidence supports it.','You are asked to propose one practical AI-assisted workflow that could reduce manual effort for lending coaches.','Create the workflow blueprint, review gate, pilot measures and stop conditions for your chosen task.','What should determine whether the workflow scales?',['Evidence that quality, control and usefulness meet the defined criteria.','Whether the demo receives positive feedback.','Whether AI can run the entire process without interruption.'],0,'Automation implementation pack'),

    L(6,1,'Choose the right problem','A capstone starts with a real workplace problem that is frequent enough to matter, narrow enough to test and safe enough to improve without changing core policy or accountability.','Several lending coaching activities take time each week, but not all are suitable for AI assistance.','Choose one problem and define the current process, user, pain, evidence and success measure without proposing a solution yet.','What makes a strong capstone problem?',['It is specific, measurable and connected to real work.','It uses the newest AI capability available.','It replaces as much human work as possible.'],0,'Capstone problem brief'),
    L(6,2,'Design the controlled solution','Design the smallest useful AI-assisted solution around the problem. Define approved inputs, the AI task, verification, output, human owner, privacy controls and what remains deliberately manual.','Your capstone problem now has a clear current process and success measure.','Create the controlled solution design, including what AI will do, what it will not do and where human approval sits.','What is the strongest solution design?',['The smallest useful workflow with clear boundaries, controls and ownership.','The most automated workflow possible.','A broad assistant that can handle any related task.'],0,'Controlled solution design'),
    L(6,3,'Measure value and risk','A useful implementation measures both benefit and control. Track time, quality, rework, user effort, exceptions and verification failures. Improvement is only real when evidence beats the current process.','Your capstone pilot has been used for several weeks by a small group of lending coaches.','Define the evidence you would collect to decide whether the solution should stop, change, continue or scale.','Which measure set is strongest?',['Time saved only.','Benefit measures plus quality, exceptions, verification failures and user effort.','Number of AI prompts submitted.'],1,'Value and risk scorecard'),
    L(6,4,'Capstone: make the recommendation','Turn the evidence into a clear recommendation: problem, controlled solution, pilot evidence, risks, what remains human and the next decision. The goal is the best evidence-based call, not proving AI should be used.','You must present the capstone outcome to the people responsible for deciding what happens next.','Write a one-page final recommendation covering the problem, solution, evidence, controls, risks, decision and next step.','What is the capstone final standard?',['A persuasive case for AI adoption.','An evidence-based recommendation with clear controls and human accountability.','A technically detailed description of the AI model.'],1,'Capstone recommendation')
  ];

  function L(module, lesson, title, concept, scenario, exercise, checkQuestion, answers, correct, toolkitTitle, correctFeedback, incorrectFeedback) {
    return { module, lesson, title, concept, scenario, exercise, checkQuestion, answers, correct, toolkitTitle, correctFeedback, incorrectFeedback };
  }

  window.ACADEMY_COURSE = { MODULES, LESSONS };
})();
